/**
 * build-book-context — Generates a running per-book context file from the
 * published-and-review chapters of each book. The result is committed to
 * the repo at src/data/book-context/<canon>/<book-slug>.md so future
 * chapter-drafting sessions can read it before drafting a new chapter and
 * carry consistent themes, characters, cross-references, and narrative facts
 * across the book.
 *
 * Triggered by the prebuild npm script (alongside build-cross-reference-index).
 */
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { REPO_ROOT, CONTENT_DIR } from './lib/paths';
import { canons, canonSlugs, type CanonSlug } from './lib/canons';

const OUT_BASE = path.join(REPO_ROOT, 'src', 'data', 'book-context');

interface ChapterData {
  canon: CanonSlug;
  bookSlug: string;
  bookName: string;
  chapter: number;
  title?: string;
  highlightSummary: string;
  themes: string[];
  christReferences: { verse: number; name: string; note?: string }[];
  status: string;
}

function walk(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith('.mdx')) out.push(full);
  }
  return out;
}

function loadChapters(): ChapterData[] {
  const out: ChapterData[] = [];
  for (const file of walk(CONTENT_DIR)) {
    const raw = fs.readFileSync(file, 'utf8');
    const { data } = matter(raw);
    // Include all statuses (draft, review, published). Draft chapters are
    // useful context for the next chapter in a batch — the agent's own
    // prior in-progress work should inform the next draft. Status is
    // recorded per-chapter in the output so a reviewer can tell what's
    // already been promoted.
    if (!['draft', 'review', 'published'].includes(data.status)) continue;
    out.push({
      canon: data.canon as CanonSlug,
      bookSlug: data.bookSlug,
      bookName: data.book,
      chapter: data.chapter,
      title: data.title,
      highlightSummary: data.highlightSummary ?? '',
      themes: Array.isArray(data.themes) ? data.themes : [],
      christReferences: Array.isArray(data.christReferences) ? data.christReferences : [],
      status: data.status,
    });
  }
  return out;
}

function generateBookContext(
  canon: CanonSlug,
  bookSlug: string,
  bookName: string,
  totalChapters: number,
  chapters: ChapterData[],
): string {
  const sorted = [...chapters].sort((a, b) => a.chapter - b.chapter);
  const built = new Date().toISOString();

  const themeMap = new Map<string, number[]>();
  for (const c of sorted) {
    for (const t of c.themes) {
      const arr = themeMap.get(t) ?? [];
      arr.push(c.chapter);
      themeMap.set(t, arr);
    }
  }

  const christMap = new Map<string, { chapter: number; verse: number; note?: string }[]>();
  for (const c of sorted) {
    for (const cr of c.christReferences) {
      const arr = christMap.get(cr.name) ?? [];
      arr.push({ chapter: c.chapter, verse: cr.verse, note: cr.note });
      christMap.set(cr.name, arr);
    }
  }

  const lines: string[] = [];
  lines.push(`# Book Context: ${bookName}`);
  lines.push('');
  lines.push(`*Auto-generated by \`scripts/build-book-context.ts\` during prebuild.*  `);
  lines.push(`Canon: \`${canon}\` &middot; bookSlug: \`${bookSlug}\``);
  lines.push('');
  lines.push(`Last built: ${built}`);
  lines.push(`Chapters covered: ${sorted.length} of ${totalChapters} (all statuses)`);
  lines.push('');
  lines.push('---');
  lines.push('');

  if (sorted.length === 0) {
    lines.push('No drafted chapters yet — this book\'s context file will populate as chapters are added.');
    lines.push('');
    return lines.join('\n');
  }

  // Themes
  lines.push('## Themes established across drafted chapters');
  lines.push('');
  if (themeMap.size === 0) {
    lines.push('*(none yet)*');
  } else {
    const themesSorted = [...themeMap.entries()].sort((a, b) => b[1].length - a[1].length);
    for (const [theme, chs] of themesSorted) {
      lines.push(`- **${theme}** — chapter${chs.length === 1 ? '' : 's'} ${chs.join(', ')}`);
    }
  }
  lines.push('');

  // Christ references
  lines.push('## Christ references across drafted chapters');
  lines.push('');
  if (christMap.size === 0) {
    lines.push('*(none yet)*');
  } else {
    for (const [name, refs] of christMap) {
      const formatted = refs.map((r) => `${r.chapter}:${r.verse}${r.note ? ` (${r.note})` : ''}`).join('; ');
      lines.push(`- **${name}** — ${formatted}`);
    }
  }
  lines.push('');

  // Per-chapter highlights
  lines.push('## Per-chapter highlights');
  lines.push('');
  for (const c of sorted) {
    const heading = c.title ? `Chapter ${c.chapter} — ${c.title}` : `Chapter ${c.chapter}`;
    lines.push(`### ${heading}`);
    lines.push('');
    lines.push(`*status:* ${c.status}`);
    if (c.themes.length > 0) lines.push(`*themes:* ${c.themes.join(', ')}`);
    lines.push('');
    lines.push(c.highlightSummary.trim());
    lines.push('');
  }

  return lines.join('\n');
}

function main(): void {
  fs.mkdirSync(OUT_BASE, { recursive: true });
  const chapters = loadChapters();

  let written = 0;
  for (const canon of canonSlugs) {
    for (const book of canons[canon].books) {
      const matching = chapters.filter(
        (c) => c.canon === canon && c.bookSlug === book.slug,
      );
      // Skip writing files for books with zero drafted chapters AND zero
      // published prior context — keeps the directory uncluttered. A book
      // gets its first context file the moment its first chapter reaches
      // status: review.
      if (matching.length === 0) continue;
      const md = generateBookContext(canon, book.slug, book.name, book.chapterCount, matching);
      const outDir = path.join(OUT_BASE, canon);
      const outFile = path.join(outDir, `${book.slug}.md`);
      fs.mkdirSync(outDir, { recursive: true });
      fs.writeFileSync(outFile, md, 'utf8');
      written++;
    }
  }
  console.log(`✓ build-book-context wrote ${written} book-context file(s) to ${path.relative(REPO_ROOT, OUT_BASE)}/`);
}

main();
